const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const LIBSQL_URL = process.env.LIBSQL_URL;
const LIBSQL_AUTH_TOKEN = process.env.LIBSQL_AUTH_TOKEN;

export { OPENAI_API_KEY, LIBSQL_URL, LIBSQL_AUTH_TOKEN };
